//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualCrypt.Language.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualCrypt.Language.Strings.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.visualcrypt.
        /// </summary>
        public static string constUntitledDotVisualCrypt {
            get {
                return ResourceManager.GetString("constUntitledDotVisualCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating MAC....
        /// </summary>
        public static string encProgr_CalculatingMAC {
            get {
                return ResourceManager.GetString("encProgr_CalculatingMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting MAC....
        /// </summary>
        public static string encProgr_DecryptingMAC {
            get {
                return ResourceManager.GetString("encProgr_DecryptingMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting Message....
        /// </summary>
        public static string encProgr_DecryptingMessage {
            get {
                return ResourceManager.GetString("encProgr_DecryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting Random Key....
        /// </summary>
        public static string encProgr_DecryptingRandomKey {
            get {
                return ResourceManager.GetString("encProgr_DecryptingRandomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting MAC....
        /// </summary>
        public static string encProgr_EncryptingMAC {
            get {
                return ResourceManager.GetString("encProgr_EncryptingMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Message....
        /// </summary>
        public static string encProgr_EncryptingMessage {
            get {
                return ResourceManager.GetString("encProgr_EncryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Random Key....
        /// </summary>
        public static string encProgr_EncryptingRandomKey {
            get {
                return ResourceManager.GetString("encProgr_EncryptingRandomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Key....
        /// </summary>
        public static string encProgr_ProcessingKey {
            get {
                return ResourceManager.GetString("encProgr_ProcessingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualCrypt {0}, AES 256 Bit, 2^{1} Rounds , {2} Ch..
        /// </summary>
        public static string encrpytedStatusbarText {
            get {
                return ResourceManager.GetString("encrpytedStatusbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World!.
        /// </summary>
        public static string Hello_World {
            get {
                return ResourceManager.GetString("Hello_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string miEdit {
            get {
                return ResourceManager.GetString("miEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string miEditCopy {
            get {
                return ResourceManager.GetString("miEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string miEditCut {
            get {
                return ResourceManager.GetString("miEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Line.
        /// </summary>
        public static string miEditDeleteLine {
            get {
                return ResourceManager.GetString("miEditDeleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string miEditFind {
            get {
                return ResourceManager.GetString("miEditFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string miEditFindNext {
            get {
                return ResourceManager.GetString("miEditFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string miEditFindPrevious {
            get {
                return ResourceManager.GetString("miEditFindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To....
        /// </summary>
        public static string miEditGoTo {
            get {
                return ResourceManager.GetString("miEditGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date, Time.
        /// </summary>
        public static string miEditInsertDateTime {
            get {
                return ResourceManager.GetString("miEditInsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string miEditPaste {
            get {
                return ResourceManager.GetString("miEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string miEditRedo {
            get {
                return ResourceManager.GetString("miEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        public static string miEditReplace {
            get {
                return ResourceManager.GetString("miEditReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string miEditSelectAll {
            get {
                return ResourceManager.GetString("miEditSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string miEditUndo {
            get {
                return ResourceManager.GetString("miEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string miFile {
            get {
                return ResourceManager.GetString("miFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string miFileExit {
            get {
                return ResourceManager.GetString("miFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Cleartext....
        /// </summary>
        public static string miFileExportClearText {
            get {
                return ResourceManager.GetString("miFileExportClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import With Encoding....
        /// </summary>
        public static string miFileImportWithEnconding {
            get {
                return ResourceManager.GetString("miFileImportWithEnconding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string miFileNew {
            get {
                return ResourceManager.GetString("miFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string miFileOpen {
            get {
                return ResourceManager.GetString("miFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        public static string miFilePrint {
            get {
                return ResourceManager.GetString("miFilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string miFileSave {
            get {
                return ResourceManager.GetString("miFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string miFileSaveAs {
            get {
                return ResourceManager.GetString("miFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string miFormat {
            get {
                return ResourceManager.GetString("miFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellchecking.
        /// </summary>
        public static string miFormatCheckSpelling {
            get {
                return ResourceManager.GetString("miFormatCheckSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font....
        /// </summary>
        public static string miFormatFont {
            get {
                return ResourceManager.GetString("miFormatFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string miFormatWordWrap {
            get {
                return ResourceManager.GetString("miFormatWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string miHelp {
            get {
                return ResourceManager.GetString("miHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About VisualCrypt....
        /// </summary>
        public static string miHelpAbout {
            get {
                return ResourceManager.GetString("miHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log....
        /// </summary>
        public static string miHelpLog {
            get {
                return ResourceManager.GetString("miHelpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help Online.
        /// </summary>
        public static string miHelpViewOnline {
            get {
                return ResourceManager.GetString("miHelpViewOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualCrypt.
        /// </summary>
        public static string miVC {
            get {
                return ResourceManager.GetString("miVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password....
        /// </summary>
        public static string miVCChangePassword {
            get {
                return ResourceManager.GetString("miVCChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string miVCDecrypt {
            get {
                return ResourceManager.GetString("miVCDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string miVCEncrypt {
            get {
                return ResourceManager.GetString("miVCEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password....
        /// </summary>
        public static string miVCSetPassword {
            get {
                return ResourceManager.GetString("miVCSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string miVCSettings {
            get {
                return ResourceManager.GetString("miVCSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string miView {
            get {
                return ResourceManager.GetString("miView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string miViewLanguage {
            get {
                return ResourceManager.GetString("miViewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar.
        /// </summary>
        public static string miViewStatusBar {
            get {
                return ResourceManager.GetString("miViewStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Area.
        /// </summary>
        public static string miViewToolArea {
            get {
                return ResourceManager.GetString("miViewToolArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string miViewZoomIn {
            get {
                return ResourceManager.GetString("miViewZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom ({0}%).
        /// </summary>
        public static string miViewZoomLevelText {
            get {
                return ResourceManager.GetString("miViewZoomLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string miViewZoomOut {
            get {
                return ResourceManager.GetString("miViewZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or corrupted/forged message..
        /// </summary>
        public static string msgPasswordError {
            get {
                return ResourceManager.GetString("msgPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting:.
        /// </summary>
        public static string operationDecryption {
            get {
                return ResourceManager.GetString("operationDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting the file being opened:.
        /// </summary>
        public static string operationDecryptOpenedFile {
            get {
                return ResourceManager.GetString("operationDecryptOpenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting and saving:.
        /// </summary>
        public static string operationEncryptAndSave {
            get {
                return ResourceManager.GetString("operationEncryptAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting:.
        /// </summary>
        public static string operationEncryption {
            get {
                return ResourceManager.GetString("operationEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln {0}, Col {1} | Pos {2}/{3}.
        /// </summary>
        public static string plaintextStatusbarPositionInfo {
            get {
                return ResourceManager.GetString("plaintextStatusbarPositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaintext | {0} | {1}.
        /// </summary>
        public static string plaintextStatusbarText {
            get {
                return ResourceManager.GetString("plaintextStatusbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string termCancel {
            get {
                return ResourceManager.GetString("termCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string termCopyToClipboard {
            get {
                return ResourceManager.GetString("termCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string termDecrypt {
            get {
                return ResourceManager.GetString("termDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt!.
        /// </summary>
        public static string termEncrypt {
            get {
                return ResourceManager.GetString("termEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string termPassword {
            get {
                return ResourceManager.GetString("termPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string termSave {
            get {
                return ResourceManager.GetString("termSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string termSetPassword {
            get {
                return ResourceManager.GetString("termSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualcrypt.com.
        /// </summary>
        public static string uriHelpUrl {
            get {
                return ResourceManager.GetString("uriHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualcrypt.com.
        /// </summary>
        public static string uriPWSpecUrl {
            get {
                return ResourceManager.GetString("uriPWSpecUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualcrypt.com.
        /// </summary>
        public static string uriSourceUrl {
            get {
                return ResourceManager.GetString("uriSourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualcrypt.com.
        /// </summary>
        public static string uriSpecUrl {
            get {
                return ResourceManager.GetString("uriSpecUrl", resourceCulture);
            }
        }
    }
}
