//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualCrypt.Language.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualCrypt.Language.Strings.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.visualcrypt.
        /// </summary>
        internal static string constUntitledDotVisualCrypt {
            get {
                return ResourceManager.GetString("constUntitledDotVisualCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating MAC....
        /// </summary>
        internal static string encProgr_CalculatingMAC {
            get {
                return ResourceManager.GetString("encProgr_CalculatingMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting MAC....
        /// </summary>
        internal static string encProgr_DecryptingMAC {
            get {
                return ResourceManager.GetString("encProgr_DecryptingMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting Message....
        /// </summary>
        internal static string encProgr_DecryptingMessage {
            get {
                return ResourceManager.GetString("encProgr_DecryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting Random Key....
        /// </summary>
        internal static string encProgr_DecryptingRandomKey {
            get {
                return ResourceManager.GetString("encProgr_DecryptingRandomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting MAC....
        /// </summary>
        internal static string encProgr_EncryptingMAC {
            get {
                return ResourceManager.GetString("encProgr_EncryptingMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Message....
        /// </summary>
        internal static string encProgr_EncryptingMessage {
            get {
                return ResourceManager.GetString("encProgr_EncryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Random Key....
        /// </summary>
        internal static string encProgr_EncryptingRandomKey {
            get {
                return ResourceManager.GetString("encProgr_EncryptingRandomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Key....
        /// </summary>
        internal static string encProgr_ProcessingKey {
            get {
                return ResourceManager.GetString("encProgr_ProcessingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualCrypt {0}, AES 256 Bit, 2^{1} Rounds , {2} Ch..
        /// </summary>
        internal static string encrpytedStatusbarText {
            get {
                return ResourceManager.GetString("encrpytedStatusbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typeface:.
        /// </summary>
        internal static string fnt_label_typeFace {
            get {
                return ResourceManager.GetString("fnt_label_typeFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family:.
        /// </summary>
        internal static string fnt_labelFontFamilies {
            get {
                return ResourceManager.GetString("fnt_labelFontFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        internal static string fnt_labelPreview {
            get {
                return ResourceManager.GetString("fnt_labelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string fnt_labelSize {
            get {
                return ResourceManager.GetString("fnt_labelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick brown fox jumps over the lazy dog.
        /// </summary>
        internal static string fnt_theQuickBrownFox {
            get {
                return ResourceManager.GetString("fnt_theQuickBrownFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World!.
        /// </summary>
        internal static string Hello_World {
            get {
                return ResourceManager.GetString("Hello_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This debug information will not be saved to a file..
        /// </summary>
        internal static string logWindowInfoText {
            get {
                return ResourceManager.GetString("logWindowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string miEdit {
            get {
                return ResourceManager.GetString("miEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string miEditCopy {
            get {
                return ResourceManager.GetString("miEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string miEditCut {
            get {
                return ResourceManager.GetString("miEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Line.
        /// </summary>
        internal static string miEditDeleteLine {
            get {
                return ResourceManager.GetString("miEditDeleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        internal static string miEditFind {
            get {
                return ResourceManager.GetString("miEditFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string miEditFindNext {
            get {
                return ResourceManager.GetString("miEditFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        internal static string miEditFindPrevious {
            get {
                return ResourceManager.GetString("miEditFindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To....
        /// </summary>
        internal static string miEditGoTo {
            get {
                return ResourceManager.GetString("miEditGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date, Time.
        /// </summary>
        internal static string miEditInsertDateTime {
            get {
                return ResourceManager.GetString("miEditInsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string miEditPaste {
            get {
                return ResourceManager.GetString("miEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string miEditRedo {
            get {
                return ResourceManager.GetString("miEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        internal static string miEditReplace {
            get {
                return ResourceManager.GetString("miEditReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string miEditSelectAll {
            get {
                return ResourceManager.GetString("miEditSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string miEditUndo {
            get {
                return ResourceManager.GetString("miEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string miFile {
            get {
                return ResourceManager.GetString("miFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string miFileExit {
            get {
                return ResourceManager.GetString("miFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Cleartext....
        /// </summary>
        internal static string miFileExportClearText {
            get {
                return ResourceManager.GetString("miFileExportClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import With Encoding....
        /// </summary>
        internal static string miFileImportWithEnconding {
            get {
                return ResourceManager.GetString("miFileImportWithEnconding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string miFileNew {
            get {
                return ResourceManager.GetString("miFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string miFileOpen {
            get {
                return ResourceManager.GetString("miFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        internal static string miFilePrint {
            get {
                return ResourceManager.GetString("miFilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string miFileSave {
            get {
                return ResourceManager.GetString("miFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string miFileSaveAs {
            get {
                return ResourceManager.GetString("miFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string miFormat {
            get {
                return ResourceManager.GetString("miFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellchecking.
        /// </summary>
        internal static string miFormatCheckSpelling {
            get {
                return ResourceManager.GetString("miFormatCheckSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font....
        /// </summary>
        internal static string miFormatFont {
            get {
                return ResourceManager.GetString("miFormatFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        internal static string miFormatWordWrap {
            get {
                return ResourceManager.GetString("miFormatWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string miHelp {
            get {
                return ResourceManager.GetString("miHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About VisualCrypt....
        /// </summary>
        internal static string miHelpAbout {
            get {
                return ResourceManager.GetString("miHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log....
        /// </summary>
        internal static string miHelpLog {
            get {
                return ResourceManager.GetString("miHelpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help Online.
        /// </summary>
        internal static string miHelpViewOnline {
            get {
                return ResourceManager.GetString("miHelpViewOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualCrypt.
        /// </summary>
        internal static string miVC {
            get {
                return ResourceManager.GetString("miVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password....
        /// </summary>
        internal static string miVCChangePassword {
            get {
                return ResourceManager.GetString("miVCChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string miVCDecrypt {
            get {
                return ResourceManager.GetString("miVCDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string miVCEncrypt {
            get {
                return ResourceManager.GetString("miVCEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password....
        /// </summary>
        internal static string miVCSetPassword {
            get {
                return ResourceManager.GetString("miVCSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptography Settings....
        /// </summary>
        internal static string miVCSettings {
            get {
                return ResourceManager.GetString("miVCSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string miView {
            get {
                return ResourceManager.GetString("miView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string miViewLanguage {
            get {
                return ResourceManager.GetString("miViewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar.
        /// </summary>
        internal static string miViewStatusBar {
            get {
                return ResourceManager.GetString("miViewStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Area.
        /// </summary>
        internal static string miViewToolArea {
            get {
                return ResourceManager.GetString("miViewToolArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string miViewZoomIn {
            get {
                return ResourceManager.GetString("miViewZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom ({0}%).
        /// </summary>
        internal static string miViewZoomLevelText {
            get {
                return ResourceManager.GetString("miViewZoomLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string miViewZoomOut {
            get {
                return ResourceManager.GetString("miViewZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes?.
        /// </summary>
        internal static string msgDiscardChanges {
            get {
                return ResourceManager.GetString("msgDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is neither text nor VisualCrypt - display with Hex View?\r\n\r\nIf file is very large the editor may become less responsive..
        /// </summary>
        internal static string msgFileIsBinary {
            get {
                return ResourceManager.GetString("msgFileIsBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string msgFindCouldNotBeFound {
            get {
                return ResourceManager.GetString("msgFindCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match for &apos;{0}&apos; could be found..
        /// </summary>
        internal static string msgFindRegExNoMatch {
            get {
                return ResourceManager.GetString("msgFindRegExNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid VisualCrypt format - Cannot decrypt this..
        /// </summary>
        internal static string msgFormatError {
            get {
                return ResourceManager.GetString("msgFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Filename..
        /// </summary>
        internal static string msgInvalidFilename {
            get {
                return ResourceManager.GetString("msgInvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found - Search again from the top of the document?.
        /// </summary>
        internal static string msgNothingFoundSearchFromStart {
            get {
                return ResourceManager.GetString("msgNothingFoundSearchFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or corrupted/forged message..
        /// </summary>
        internal static string msgPasswordError {
            get {
                return ResourceManager.GetString("msgPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Regular Expression Syntax.
        /// </summary>
        internal static string msgReplaceInvalidRegEx {
            get {
                return ResourceManager.GetString("msgReplaceInvalidRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurrences were replaced..
        /// </summary>
        internal static string msgReplaceOccucancesReplaced {
            get {
                return ResourceManager.GetString("msgReplaceOccucancesReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting:.
        /// </summary>
        internal static string operationDecryption {
            get {
                return ResourceManager.GetString("operationDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting loaded file:.
        /// </summary>
        internal static string operationDecryptOpenedFile {
            get {
                return ResourceManager.GetString("operationDecryptOpenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting and saving:.
        /// </summary>
        internal static string operationEncryptAndSave {
            get {
                return ResourceManager.GetString("operationEncryptAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting:.
        /// </summary>
        internal static string operationEncryption {
            get {
                return ResourceManager.GetString("operationEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln {0}, Col {1} | Pos {2}/{3}.
        /// </summary>
        internal static string plaintextStatusbarPositionInfo {
            get {
                return ResourceManager.GetString("plaintextStatusbarPositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaintext | {0} | {1}.
        /// </summary>
        internal static string plaintextStatusbarText {
            get {
                return ResourceManager.GetString("plaintextStatusbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualCrypt 2 (AES 256 Bit, BCrypt - Multi).
        /// </summary>
        internal static string sett_combo_VisualCrypt2 {
            get {
                return ResourceManager.GetString("sett_combo_VisualCrypt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source code.
        /// </summary>
        internal static string sett_linktext_Source {
            get {
                return ResourceManager.GetString("sett_linktext_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec.
        /// </summary>
        internal static string sett_linktext_Spec {
            get {
                return ResourceManager.GetString("sett_linktext_Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCrypt/AES Rounds:.
        /// </summary>
        internal static string sett_text_BCryptAESRounds {
            get {
                return ResourceManager.GetString("sett_text_BCryptAESRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default: 2.
        /// </summary>
        internal static string sett_text_default_2_power {
            get {
                return ResourceManager.GetString("sett_text_default_2_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Method:.
        /// </summary>
        internal static string sett_text_EncrpytionMethod {
            get {
                return ResourceManager.GetString("sett_text_EncrpytionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or view the.
        /// </summary>
        internal static string sett_text_orViewThe {
            get {
                return ResourceManager.GetString("sett_text_orViewThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the.
        /// </summary>
        internal static string sett_text_ReadThe {
            get {
                return ResourceManager.GetString("sett_text_ReadThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: A high value will turn encryption and decryption into a very time consuming operation..
        /// </summary>
        internal static string sett_warn_high {
            get {
                return ResourceManager.GetString("sett_warn_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: A low value faciliates brute force and dictionary attacks..
        /// </summary>
        internal static string sett_warn_low {
            get {
                return ResourceManager.GetString("sett_warn_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting influences the required computational work to create the BCrypt hash. A higher value means more work..
        /// </summary>
        internal static string sett_warn_neutral {
            get {
                return ResourceManager.GetString("sett_warn_neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password/-phrase:.
        /// </summary>
        internal static string spd_lbl_PasswordOrPhrase {
            get {
                return ResourceManager.GetString("spd_lbl_PasswordOrPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password.
        /// </summary>
        internal static string spd_linktext_GeneratePassword {
            get {
                return ResourceManager.GetString("spd_linktext_GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Password.
        /// </summary>
        internal static string spd_linktext_PrintPassword {
            get {
                return ResourceManager.GetString("spd_linktext_PrintPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualCrypt Passwords.
        /// </summary>
        internal static string spd_linktext_VisualCryptPasswords {
            get {
                return ResourceManager.GetString("spd_linktext_VisualCryptPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is effectively empty - are you sure?.
        /// </summary>
        internal static string spd_msgPasswordEffectivelyEmpty {
            get {
                return ResourceManager.GetString("spd_msgPasswordEffectivelyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use empty password?.
        /// </summary>
        internal static string spd_msgUseEmptyPassword {
            get {
                return ResourceManager.GetString("spd_msgUseEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} significant Unicode Characters.
        /// </summary>
        internal static string spd_msgXofYUnicodeChars {
            get {
                return ResourceManager.GetString("spd_msgXofYUnicodeChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (256 Bit Random Data).
        /// </summary>
        internal static string spd_text_from256BitRD {
            get {
                return ResourceManager.GetString("spd_text_from256BitRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more about.
        /// </summary>
        internal static string spd_text_ReadMoreAbout {
            get {
                return ResourceManager.GetString("spd_text_ReadMoreAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string spdm_Change_OK {
            get {
                return ResourceManager.GetString("spdm_Change_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string spdm_Change_Title {
            get {
                return ResourceManager.GetString("spdm_Change_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password and decrypt.
        /// </summary>
        internal static string spdm_CorrectPassword_OK {
            get {
                return ResourceManager.GetString("spdm_CorrectPassword_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is not correct.
        /// </summary>
        internal static string spdm_CorrectPassword_Title {
            get {
                return ResourceManager.GetString("spdm_CorrectPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string spdm_Set_OK {
            get {
                return ResourceManager.GetString("spdm_Set_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string spdm_Set_Title {
            get {
                return ResourceManager.GetString("spdm_Set_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string spdm_SetAndDecrypt_OK {
            get {
                return ResourceManager.GetString("spdm_SetAndDecrypt_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password &amp; Decrypt.
        /// </summary>
        internal static string spdm_SetAndDecrypt_Title {
            get {
                return ResourceManager.GetString("spdm_SetAndDecrypt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt loaded file.
        /// </summary>
        internal static string spdm_SetAndDecryptLoadedFile_OK {
            get {
                return ResourceManager.GetString("spdm_SetAndDecryptLoadedFile_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password to decrypt loaded file.
        /// </summary>
        internal static string spdm_SetAndDecryptLoadedFile_Title {
            get {
                return ResourceManager.GetString("spdm_SetAndDecryptLoadedFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string spdm_SetAndEncrypt_OK {
            get {
                return ResourceManager.GetString("spdm_SetAndEncrypt_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password &amp; Encrypt.
        /// </summary>
        internal static string spdm_SetAndEncrypt_Title {
            get {
                return ResourceManager.GetString("spdm_SetAndEncrypt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt and Save.
        /// </summary>
        internal static string spdm_SetAndEncryptAndSave_OK {
            get {
                return ResourceManager.GetString("spdm_SetAndEncryptAndSave_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password, Encrypt and Save.
        /// </summary>
        internal static string spdm_SetAndEncryptAndSave_Title {
            get {
                return ResourceManager.GetString("spdm_SetAndEncryptAndSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary File.
        /// </summary>
        internal static string termBinary {
            get {
                return ResourceManager.GetString("termBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string termCancel {
            get {
                return ResourceManager.GetString("termCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string termChangePassword {
            get {
                return ResourceManager.GetString("termChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string termClear {
            get {
                return ResourceManager.GetString("termClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Password.
        /// </summary>
        internal static string termClearPassword {
            get {
                return ResourceManager.GetString("termClearPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string termClose {
            get {
                return ResourceManager.GetString("termClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string termCopyToClipboard {
            get {
                return ResourceManager.GetString("termCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string termDecrypt {
            get {
                return ResourceManager.GetString("termDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string termDefaults {
            get {
                return ResourceManager.GetString("termDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string termEncrypt {
            get {
                return ResourceManager.GetString("termEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string termFind {
            get {
                return ResourceManager.GetString("termFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string termGo {
            get {
                return ResourceManager.GetString("termGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string termNotes {
            get {
                return ResourceManager.GetString("termNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string termOK {
            get {
                return ResourceManager.GetString("termOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string termPassword {
            get {
                return ResourceManager.GetString("termPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string termReplace {
            get {
                return ResourceManager.GetString("termReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        internal static string termReplaceAll {
            get {
                return ResourceManager.GetString("termReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string termSave {
            get {
                return ResourceManager.GetString("termSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string termSetPassword {
            get {
                return ResourceManager.GetString("termSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Clear Text (Encoding: {0}).
        /// </summary>
        internal static string titleExportCleartext {
            get {
                return ResourceManager.GetString("titleExportCleartext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import with encoding: {0}.
        /// </summary>
        internal static string titleImportWithEncoding {
            get {
                return ResourceManager.GetString("titleImportWithEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number (1-.
        /// </summary>
        internal static string toolAreaGoLineNo {
            get {
                return ResourceManager.GetString("toolAreaGoLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string toolAreaMatchCase {
            get {
                return ResourceManager.GetString("toolAreaMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        internal static string toolAreaMatchWholeWord {
            get {
                return ResourceManager.GetString("toolAreaMatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regular Expressions.
        /// </summary>
        internal static string toolAreaRegularEx {
            get {
                return ResourceManager.GetString("toolAreaRegularEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        internal static string toolAreaReplaceWith {
            get {
                return ResourceManager.GetString("toolAreaReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search up.
        /// </summary>
        internal static string toolAreaSearchUp {
            get {
                return ResourceManager.GetString("toolAreaSearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualcrypt.com/category/faq.
        /// </summary>
        internal static string uriHelpUrl {
            get {
                return ResourceManager.GetString("uriHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualcrypt.com/post/password-quality.
        /// </summary>
        internal static string uriPWSpecUrl {
            get {
                return ResourceManager.GetString("uriPWSpecUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/VisualCrypt/VisualCrypt.
        /// </summary>
        internal static string uriSourceUrl {
            get {
                return ResourceManager.GetString("uriSourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://visualcrypt.com/post/visualcrypt-2-encryption-standard-specification.
        /// </summary>
        internal static string uriSpecUrl {
            get {
                return ResourceManager.GetString("uriSpecUrl", resourceCulture);
            }
        }
    }
}
